#
# docker-compose build && docker-compose push
#
version: "3.5"
services:
  dev:
    container_name: api-test
    env_file:
      - .env
    image: api-test:1.0.0
    build:
      context: .
      target: development
      network: host
    command: npm run dev
    ports:
      - ${PORT}:${PORT}
    # network_mode: host
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
